# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GIF Search' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Internal Interfaces
  pod 'NetworkInterfaces', :path => '../NetworkInterfaces.podspec'
  pod 'GIFFoundation', :path => '../GIFFoundation.podspec'
  pod 'GIFInterfaces', :path => '../GIFInterfaces.podspec'
  
  #External Frameworks
  pod 'SDWebImage', '~> 5.0'

  # Pods for GIF Search
  target 'GIF SearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GIF SearchUITests' do
    # Pods for testing
  end

end
